version: "3.9"
services:
    web:
        build: 
            context: .
            args:
                APP_REQUIREMENTS: requirements-dev.txt
        command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
        volumes:
            - './:/opt/technest'
        ports:
            - 8883:80
        environment:
            LOG_LEVEL: DEBUG

